urls:
  # Ansible
  - https://docs.ansible.com/ansible/latest/getting_started/index.html
  - https://docs.ansible.com/ansible/latest/playbook_guide/index.html
  - https://docs.ansible.com/ansible/latest/inventory_guide/index.html
  - https://docs.ansible.com/ansible/latest/command_guide/index.html
  
  # Terraform
  - https://developer.hashicorp.com/terraform/intro
  - https://developer.hashicorp.com/terraform/language
  - https://developer.hashicorp.com/terraform/cli
  
  # Prometheus
  - https://prometheus.io/docs/introduction/overview/
  - https://prometheus.io/docs/prometheus/latest/querying/basics/
  
  # Grafana
  - https://grafana.com/docs/grafana/latest/getting-started/
